// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using SuperCreation.Abp.CodeDocs.Code;
using System.Collections.Generic;

// ReSharper disable once CheckNamespace
namespace SuperCreation.Abp.CodeDocs.Code.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IClassParameterAppService), typeof(ClassParameterClientProxy))]
public partial class ClassParameterClientProxy : ClientProxyBase<IClassParameterAppService>, IClassParameterAppService
{
    public virtual async Task<List<ClassParameterDto>> GetAllWithClassIdAsync(Guid classId)
    {
        return await RequestAsync<List<ClassParameterDto>>(nameof(GetAllWithClassIdAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), classId }
        });
    }

    public virtual async Task<bool> CreateAsync(ClassParameterCreateUpdateDto input)
    {
        return await RequestAsync<bool>(nameof(CreateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ClassParameterCreateUpdateDto), input }
        });
    }

    public virtual async Task DeleteAsync(Guid classId, string name)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), classId },
            { typeof(string), name }
        });
    }

    public virtual async Task<bool> UpdateAsync(ClassParameterCreateUpdateDto input)
    {
        return await RequestAsync<bool>(nameof(UpdateAsync), new ClientProxyRequestTypeValue
        {
            { typeof(ClassParameterCreateUpdateDto), input }
        });
    }
}
